services:
  db:
    image: mongo:8
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
    volumes:
      - db-volume:/data/db
  # storage:
  #   image: quay.io/minio/minio:latest
  #   command: server /data --console-address ":9001"
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=admin@eaportal123
  #   ports:
  #     - "127.0.0.1:9000:9000"
  #     - "127.0.0.1:9001:9001"
  #   volumes:
  #     - storage-volume:/data
  #   restart: always
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  # mail:
  #   image: axllent/mailpit:latest
  #   ports:
  #     - "127.0.0.1:1025:1025"
  #     - "127.0.0.1:8025:8025"
  #   environment:
  #     MP_MAX_MESSAGES: 5000
  #     MP_DATA_FILE: /data/mailpit.db
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
  #     MP_UI_AUTH: admin:admin@eaportal123
  #   volumes:
  #     - mail-volume:/data
  #   restart: always
  #   healthcheck:
  #     test:
  #       ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8025/livez"]
volumes:
  db-volume:
  # storage-volume:
  # mail-volume:
